- name: Deploy using token
  env:
    TOKEN: ${{ secrets.GH_TOKEN }}
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git remote set-url origin https://x-access-token:${TOKEN}@github.com/vanguriaishwarya/my-first-cicd.git
    git add .
    git commit -m "Automated deployment"
    git push origin main
